# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pa_ptr_pyqtIWmPni.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from mplwidget import MplWidget
from mplwidget2 import MplWidget2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1160, 700)
        self.actionAjuda = QAction(MainWindow)
        self.actionAjuda.setObjectName(u"actionAjuda")
        self.actionSobre = QAction(MainWindow)
        self.actionSobre.setObjectName(u"actionSobre")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1161, 671))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 47, 13))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 290, 47, 13))
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 371, 251))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(25)
        self.frame.setMidLineWidth(8)
        self.btCarregar_3 = QPushButton(self.frame)
        self.btCarregar_3.setObjectName(u"btCarregar_3")
        self.btCarregar_3.setGeometry(QRect(100, 210, 75, 23))
        icon = QIcon()
        icon.addFile(u"resources/up_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btCarregar_3.setIcon(icon)
        self.btLimpar_3 = QPushButton(self.frame)
        self.btLimpar_3.setObjectName(u"btLimpar_3")
        self.btLimpar_3.setGeometry(QRect(180, 210, 75, 23))
        icon1 = QIcon()
        icon1.addFile(u"resources/lixeira.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btLimpar_3.setIcon(icon1)
        self.layoutWidget_3 = QWidget(self.frame)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 10, 355, 190))
        self.gridLayout_3 = QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.txAnimal_3 = QLineEdit(self.layoutWidget_3)
        self.txAnimal_3.setObjectName(u"txAnimal_3")

        self.gridLayout_3.addWidget(self.txAnimal_3, 3, 1, 1, 1)

        self.label_26 = QLabel(self.layoutWidget_3)
        self.label_26.setObjectName(u"label_26")

        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)

        self.label_23 = QLabel(self.layoutWidget_3)
        self.label_23.setObjectName(u"label_23")

        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)

        self.label_29 = QLabel(self.layoutWidget_3)
        self.label_29.setObjectName(u"label_29")

        self.gridLayout_3.addWidget(self.label_29, 3, 0, 1, 1)

        self.btArquivoBruto_3 = QPushButton(self.layoutWidget_3)
        self.btArquivoBruto_3.setObjectName(u"btArquivoBruto_3")
        icon2 = QIcon()
        icon2.addFile(u"resources/img_folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btArquivoBruto_3.setIcon(icon2)

        self.gridLayout_3.addWidget(self.btArquivoBruto_3, 0, 2, 1, 1)

        self.btArquivoSaida_3 = QPushButton(self.layoutWidget_3)
        self.btArquivoSaida_3.setObjectName(u"btArquivoSaida_3")
        self.btArquivoSaida_3.setIcon(icon2)

        self.gridLayout_3.addWidget(self.btArquivoSaida_3, 4, 2, 1, 1)

        self.cbGrupoAnimais_3 = QComboBox(self.layoutWidget_3)
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.addItem("")
        self.cbGrupoAnimais_3.setObjectName(u"cbGrupoAnimais_3")

        self.gridLayout_3.addWidget(self.cbGrupoAnimais_3, 2, 1, 1, 1)

        self.label_28 = QLabel(self.layoutWidget_3)
        self.label_28.setObjectName(u"label_28")

        self.gridLayout_3.addWidget(self.label_28, 0, 0, 1, 1)

        self.txArquivoSaida_3 = QLineEdit(self.layoutWidget_3)
        self.txArquivoSaida_3.setObjectName(u"txArquivoSaida_3")

        self.gridLayout_3.addWidget(self.txArquivoSaida_3, 4, 1, 1, 1)

        self.txParametros_3 = QLineEdit(self.layoutWidget_3)
        self.txParametros_3.setObjectName(u"txParametros_3")

        self.gridLayout_3.addWidget(self.txParametros_3, 1, 1, 1, 1)

        self.label_24 = QLabel(self.layoutWidget_3)
        self.label_24.setObjectName(u"label_24")
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)

        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 1)

        self.btParametros_3 = QPushButton(self.layoutWidget_3)
        self.btParametros_3.setObjectName(u"btParametros_3")
        self.btParametros_3.setIcon(icon2)

        self.gridLayout_3.addWidget(self.btParametros_3, 1, 2, 1, 1)

        self.txArquivoBruto_3 = QLineEdit(self.layoutWidget_3)
        self.txArquivoBruto_3.setObjectName(u"txArquivoBruto_3")

        self.gridLayout_3.addWidget(self.txArquivoBruto_3, 0, 1, 1, 1)

        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 310, 371, 321))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.rb15IQR_3 = QRadioButton(self.frame_2)
        self.buttonGroup = QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.rb15IQR_3)
        self.rb15IQR_3.setObjectName(u"rb15IQR_3")
        self.rb15IQR_3.setGeometry(QRect(65, 84, 70, 17))
        self.rb15IQR_3.setChecked(True)
        self.rb3IQR_3 = QRadioButton(self.frame_2)
        self.buttonGroup.addButton(self.rb3IQR_3)
        self.rb3IQR_3.setObjectName(u"rb3IQR_3")
        self.rb3IQR_3.setGeometry(QRect(65, 107, 60, 17))
        self.cbEtapas_3 = QComboBox(self.frame_2)
        self.cbEtapas_3.setObjectName(u"cbEtapas_3")
        self.cbEtapas_3.setGeometry(QRect(100, 30, 221, 20))
        self.label_30 = QLabel(self.frame_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(11, 30, 33, 16))
        self.label_31 = QLabel(self.frame_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 65, 221, 16))
        self.label_31.setFont(font)
        self.label_32 = QLabel(self.frame_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 170, 151, 16))
        self.label_32.setFont(font)
        self.rbNenhum_3 = QRadioButton(self.frame_2)
        self.buttonGroup.addButton(self.rbNenhum_3)
        self.rbNenhum_3.setObjectName(u"rbNenhum_3")
        self.rbNenhum_3.setGeometry(QRect(65, 130, 62, 17))
        self.rbRice_3 = QRadioButton(self.frame_2)
        self.buttonGroup_2 = QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(u"buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbRice_3)
        self.rbRice_3.setObjectName(u"rbRice_3")
        self.rbRice_3.setGeometry(QRect(65, 190, 90, 17))
        self.rbRice_3.setChecked(True)
        self.rbEtapa_3 = QRadioButton(self.frame_2)
        self.buttonGroup_2.addButton(self.rbEtapa_3)
        self.rbEtapa_3.setObjectName(u"rbEtapa_3")
        self.rbEtapa_3.setGeometry(QRect(65, 240, 99, 17))
        self.btInicioPa_3 = QPushButton(self.frame_2)
        self.btInicioPa_3.setObjectName(u"btInicioPa_3")
        self.btInicioPa_3.setGeometry(QRect(100, 281, 160, 24))
        self.btInicioPa_3.setFont(font)
        icon3 = QIcon()
        icon3.addFile(u"resources/clock.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btInicioPa_3.setIcon(icon3)
        self.btAtualizar_3 = QPushButton(self.frame_2)
        self.btAtualizar_3.setObjectName(u"btAtualizar_3")
        self.btAtualizar_3.setGeometry(QRect(16, 281, 75, 24))
        icon4 = QIcon()
        icon4.addFile(u"resources/atualizar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btAtualizar_3.setIcon(icon4)
        self.btSalvar_3 = QPushButton(self.frame_2)
        self.btSalvar_3.setObjectName(u"btSalvar_3")
        self.btSalvar_3.setGeometry(QRect(270, 281, 75, 24))
        icon5 = QIcon()
        icon5.addFile(u"resources/floppy-disk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btSalvar_3.setIcon(icon5)
        self.horizontalSlider = QSlider(self.frame_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(80, 210, 121, 22))
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setValue(100)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.spinBox = QSpinBox(self.frame_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(231, 210, 61, 22))
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(100)
        self.spinBox.setValue(100)
        self.label_33 = QLabel(self.tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(400, 10, 47, 13))
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(400, 30, 741, 601))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.MplWidget_3 = MplWidget(self.frame_3)
        self.MplWidget_3.setObjectName(u"MplWidget_3")
        self.MplWidget_3.setGeometry(QRect(10, 10, 731, 571))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_34 = QLabel(self.tab_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 140, 47, 13))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 91, 16))
        self.frame_4 = QFrame(self.tab_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 30, 681, 101))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Plain)
        self.frame_4.setLineWidth(25)
        self.frame_4.setMidLineWidth(8)
        self.layoutWidget = QWidget(self.frame_4)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(11, 10, 551, 82))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_40 = QLabel(self.layoutWidget)
        self.label_40.setObjectName(u"label_40")

        self.gridLayout.addWidget(self.label_40, 0, 0, 1, 1)

        self.txArquivoBruto_4 = QLineEdit(self.layoutWidget)
        self.txArquivoBruto_4.setObjectName(u"txArquivoBruto_4")

        self.gridLayout.addWidget(self.txArquivoBruto_4, 0, 1, 1, 1)

        self.btArquivoBruto_4 = QPushButton(self.layoutWidget)
        self.btArquivoBruto_4.setObjectName(u"btArquivoBruto_4")
        self.btArquivoBruto_4.setIcon(icon2)

        self.gridLayout.addWidget(self.btArquivoBruto_4, 0, 2, 1, 1)

        self.label_35 = QLabel(self.layoutWidget)
        self.label_35.setObjectName(u"label_35")

        self.gridLayout.addWidget(self.label_35, 0, 3, 1, 1)

        self.label_38 = QLabel(self.layoutWidget)
        self.label_38.setObjectName(u"label_38")

        self.gridLayout.addWidget(self.label_38, 1, 0, 1, 1)

        self.txArquivoSaida_4 = QLineEdit(self.layoutWidget)
        self.txArquivoSaida_4.setObjectName(u"txArquivoSaida_4")

        self.gridLayout.addWidget(self.txArquivoSaida_4, 1, 1, 1, 1)

        self.btArquivoSaida_4 = QPushButton(self.layoutWidget)
        self.btArquivoSaida_4.setObjectName(u"btArquivoSaida_4")
        self.btArquivoSaida_4.setIcon(icon2)

        self.gridLayout.addWidget(self.btArquivoSaida_4, 1, 2, 1, 1)

        self.label_41 = QLabel(self.layoutWidget)
        self.label_41.setObjectName(u"label_41")

        self.gridLayout.addWidget(self.label_41, 2, 0, 1, 1)

        self.txAnimal_4 = QLineEdit(self.layoutWidget)
        self.txAnimal_4.setObjectName(u"txAnimal_4")

        self.gridLayout.addWidget(self.txAnimal_4, 2, 1, 1, 1)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_5.setFont(font1)

        self.gridLayout.addWidget(self.label_5, 2, 4, 1, 1)

        self.cbGrupoAnimais_4 = QComboBox(self.layoutWidget)
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.addItem("")
        self.cbGrupoAnimais_4.setObjectName(u"cbGrupoAnimais_4")

        self.gridLayout.addWidget(self.cbGrupoAnimais_4, 0, 4, 1, 1)

        self.layoutWidget1 = QWidget(self.frame_4)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(590, 20, 77, 56))
        self.gridLayout_2 = QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.btCarregar_4 = QPushButton(self.layoutWidget1)
        self.btCarregar_4.setObjectName(u"btCarregar_4")
        self.btCarregar_4.setIcon(icon)

        self.gridLayout_2.addWidget(self.btCarregar_4, 0, 0, 1, 1)

        self.btLimpar_4 = QPushButton(self.layoutWidget1)
        self.btLimpar_4.setObjectName(u"btLimpar_4")
        self.btLimpar_4.setIcon(icon1)

        self.gridLayout_2.addWidget(self.btLimpar_4, 1, 0, 1, 1)

        self.frame_6 = QFrame(self.tab_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 160, 1131, 461))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Plain)
        self.MplWidget2 = MplWidget2(self.frame_6)
        self.MplWidget2.setObjectName(u"MplWidget2")
        self.MplWidget2.setGeometry(QRect(10, 10, 1111, 441))
        self.frame_5 = QFrame(self.tab_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(700, 30, 431, 101))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Plain)
        self.label_42 = QLabel(self.frame_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(40, 40, 33, 16))
        self.cbEtapas_4 = QComboBox(self.frame_5)
        self.cbEtapas_4.setObjectName(u"cbEtapas_4")
        self.cbEtapas_4.setGeometry(QRect(80, 40, 221, 20))
        self.layoutWidget2 = QWidget(self.frame_5)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(330, 20, 77, 56))
        self.gridLayout_4 = QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btAtualizar_4 = QPushButton(self.layoutWidget2)
        self.btAtualizar_4.setObjectName(u"btAtualizar_4")
        self.btAtualizar_4.setIcon(icon4)

        self.gridLayout_4.addWidget(self.btAtualizar_4, 0, 0, 1, 1)

        self.btSalvar_4 = QPushButton(self.layoutWidget2)
        self.btSalvar_4.setObjectName(u"btSalvar_4")
        self.btSalvar_4.setIcon(icon5)

        self.gridLayout_4.addWidget(self.btSalvar_4, 1, 0, 1, 1)

        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(700, 10, 91, 16))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1160, 21))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.actionAjuda)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSobre)

        self.retranslateUi(MainWindow)
        self.spinBox.valueChanged.connect(self.horizontalSlider.setValue)
        self.horizontalSlider.valueChanged.connect(self.spinBox.setValue)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"An\u00e1lise PA & Ptr", None))
        self.actionAjuda.setText(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.actionSobre.setText(QCoreApplication.translate("MainWindow", u"Sobre", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.btCarregar_3.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_3.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"5. Arquivo Sa\u00edda", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"3. Grupo de Animais", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"4. Animal #", None))
        self.btArquivoBruto_3.setText("")
        self.btArquivoSaida_3.setText("")
        self.cbGrupoAnimais_3.setItemText(0, QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Tratados", None))
        self.cbGrupoAnimais_3.setItemText(1, QCoreApplication.translate("MainWindow", u"SHR 21 Semanas Tratados", None))
        self.cbGrupoAnimais_3.setItemText(2, QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Nao Tratados", None))
        self.cbGrupoAnimais_3.setItemText(3, QCoreApplication.translate("MainWindow", u"SHR 21 Semanas Nao Tratados", None))
        self.cbGrupoAnimais_3.setItemText(4, QCoreApplication.translate("MainWindow", u"WKY 21 Semanas Tratados", None))
        self.cbGrupoAnimais_3.setItemText(5, QCoreApplication.translate("MainWindow", u"WKY 21 Semanas Nao Tratados", None))

        self.cbGrupoAnimais_3.setCurrentText(QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Tratados", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"2. Arquivo Par\u00e2metros (PA)", None))
        self.btParametros_3.setText("")
        self.rb15IQR_3.setText(QCoreApplication.translate("MainWindow", u"1.5 * IQR", None))
        self.rb3IQR_3.setText(QCoreApplication.translate("MainWindow", u"3 * IQR", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"M\u00e9todo Detec\u00e7\u00e3o Outliers PA (Tukey)", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Janela C\u00e1lculo Tukey (PA)", None))
        self.rbNenhum_3.setText(QCoreApplication.translate("MainWindow", u"Nenhum", None))
        self.rbRice_3.setText(QCoreApplication.translate("MainWindow", u"Regra de Rice", None))
        self.rbEtapa_3.setText(QCoreApplication.translate("MainWindow", u"Etapa Completa", None))
        self.btInicioPa_3.setText(QCoreApplication.translate("MainWindow", u" Selecionar In\u00edcio (PA)", None))
        self.btAtualizar_3.setText(QCoreApplication.translate("MainWindow", u" Atualizar", None))
        self.btSalvar_3.setText(QCoreApplication.translate("MainWindow", u" Salvar", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"An\u00e1lise PA", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.btArquivoBruto_4.setText("")
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"4. Grupo de Animais", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"2. Arquivo Sa\u00edda", None))
        self.btArquivoSaida_4.setText("")
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"3. Animal #", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Arquivo Vers\u00e3o", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.cbGrupoAnimais_4.setItemText(0, QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Tratados", None))
        self.cbGrupoAnimais_4.setItemText(1, QCoreApplication.translate("MainWindow", u"SHR 21 Semanas Tratados", None))
        self.cbGrupoAnimais_4.setItemText(2, QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Nao Tratados", None))
        self.cbGrupoAnimais_4.setItemText(3, QCoreApplication.translate("MainWindow", u"SHR 21 Semanas Nao Tratados", None))
        self.cbGrupoAnimais_4.setItemText(4, QCoreApplication.translate("MainWindow", u"WKY 21 Semanas Tratados", None))
        self.cbGrupoAnimais_4.setItemText(5, QCoreApplication.translate("MainWindow", u"WKY 21 Semanas Nao Tratados", None))

        self.cbGrupoAnimais_4.setCurrentText(QCoreApplication.translate("MainWindow", u"SHR 17 Semanas Tratados", None))
        self.btCarregar_4.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_4.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.btAtualizar_4.setText(QCoreApplication.translate("MainWindow", u" Atualizar", None))
        self.btSalvar_4.setText(QCoreApplication.translate("MainWindow", u" Salvar", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"An\u00e1lise Ptr", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"An\u00e1lise Estat\u00edstica", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
    # retranslateUi

